package com.example.stylemirror_1_1.Activity;

import android.os.Bundle;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.SearchView;
import androidx.recyclerview.widget.LinearLayoutManager;

import com.example.stylemirror_1_1.R;
import com.example.stylemirror_1_1.databinding.ActivitySearchBinding;
import com.example.stylemirror_1_1.domain.PopularDomain;
import com.example.stylemirror_1_1.Adapter.SearchAdapter;

import java.util.ArrayList;
import java.util.Locale;

public class activity_search extends AppCompatActivity {

    ActivitySearchBinding binding;
    private ArrayList<PopularDomain> mList;
    private SearchAdapter adapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = ActivitySearchBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        binding.recyclerView.setHasFixedSize(true);
        binding.recyclerView.setLayoutManager(new LinearLayoutManager(this));

        mList = new ArrayList<>(); // Initialize mList before adding data
        addDataToList();

        adapter = new SearchAdapter(mList,this);
        binding.recyclerView.setAdapter(adapter);

        binding.searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
            @Override
            public boolean onQueryTextSubmit(String query) {
                return false;
            }

            @Override
            public boolean onQueryTextChange(String newText) {
                filterList(newText);
                return true;
            }
        });
    }

    private void filterList(String query) {
        if (query != null) {
            ArrayList<PopularDomain> filteredList = new ArrayList<>();
            for (PopularDomain data : mList) {
                if (data.getTitle().toLowerCase(Locale.ROOT).contains(query.toLowerCase(Locale.ROOT))) {
                    filteredList.add(data);
                }
            }

            if (filteredList.isEmpty()) {
                Toast.makeText(this, "No Data found", Toast.LENGTH_SHORT).show();
            } else {
                adapter.setFilteredList(filteredList);
            }
        }
    }

    private void addDataToList() {
        //List of Shoes
        mList.add(new PopularDomain(1,"Air Max 270 Sneakers For Men", R.drawable.shoess_1_1, R.drawable.shoess_1_2, R.drawable.shoess_1_3,5,100,8921,"Wipe with clean cloth Nike's first lifestyle Air Max brings you style, comfort and big attitude in the Nike Air Max 270. The design draws inspiration from Air Max icons, showcasing Nike's greatest innovation with its large window and fresh array of colours.","https://www.flipkart.com/nike-air-max-270-sneakers-men/p/itm1d9717048f829?pid=SHOGQZKYZYC3K2B4&cmpid=product.share.pp&_refId=PP.1f10854d-aa61-4c99-a442-686cc67a67a6.SHOGQZKYZYC3K2B4&_appId=WA"));
        mList.add(new PopularDomain(2,"Nike Viale Premium Men's Running Shoes", R.drawable.shoess_2_1, R.drawable.shoess_2_2, R.drawable.shoess_2_3,0,0,5695,"Nike Viale Premium Men's Running Shoes NIKE men's running shoes","https://www.amazon.in/Nike-Viale-Premium-Running-Numeric_7/dp/B0BTPVLLPL/ref=sr_1_4?dib=eyJ2IjoiMSJ9.hbzFw-M-hmtF21AcdjfXK3o9SF9pZNyCP4xenMzhimteP31pc2TemY-tIry1XmxJL2_zraO-yBE_yDKaiyVGDMtdj07Eh6qsOhJDfStAqdmG8nYV4-qtKc6E3nLZ5GYVh-mpC4e7GoWs2URRvrU_62ljLJ5R5obK73257xZzvAfcPntT1jDgij1YJs-Gav-JdTC9x87r2xeiL1YkzOGpFNW_63pNX1K31hyR-UGDyHg-JVF5S9HGx2WtzouzbBex.KUQ3ow71uTlLfiTteAgKMBA9rn0SXqdXKqWevspXO0c&dib_tag=se&keywords=nike+viale&qid=1709282802&sr=8-4"));
        mList.add(new PopularDomain(3,"Imba M Running Shoes For Men", R.drawable.shoess_3_1, R.drawable.shoess_3_2, R.drawable.shoess_3_3, (int) 4.1,55,1859,"","https://www.flipkart.com/adidas-imba-m-running-shoes-men/p/itmf3xjvamur7zha?pid=SHOE25GFNHVSVVTZ&cmpid=product.share.pp&_refId=PP.7653c4f6-d2ec-4dc0-8ce4-829d9de18f84.SHOE25GFNHVSVVTZ&_appId=WA"));
        mList.add(new PopularDomain(4,"BADLAV® Air Force Black Sneakers for Men", R.drawable.shoess_4_1, R.drawable.shoess_4_2, R.drawable.shoess_4_3, (int) 3.3,125,481,"Design Concept: Sports Fusion Fashion, technology used in the upper and sole material. Application of skin-friendly Suede and TPR Outsole,strict machine suture. Material: Innovative use of skin-friendly Suede for a optimal breathable comfortable & lightweight feeling.Quickly absorb sweat and drying friendly,make feet cool and dry. Sole: High-quality rubber sole for lightweight cushioning. Vertical and horizontal flex grooves give you flexibility in all directions. Don’t crease and easy to clean Characteristics: Antimicrobial lining minimizes the risk of odor causing bacteria.Anti-odor technology applied to footbed to prevent the growth of odor-causing microbes.","https://www.amazon.in/dp/B0CS9NBWHS?starsLeft=1&ref_=cm_sw_r_ud_dp_086PRN0QZT8W4PWN716G"));
        mList.add(new PopularDomain(5,"Blue Shades Clouded Sky Personalized Sneakers Lightweight Walking Shoes", R.drawable.shoess_5_1, R.drawable.shoess_5_2, R.drawable.shoess_5_3,0,0,0,"Materials: Breathable suede Upper + Non Slip Rubber Sole. Breathable suede Upper upper material make it possible that your feet to breathe freely while running or walking; Rubber sole adapts to ground stability and working strategy to optimize unique performance per bump and push. Applications: It's walking shoes, sneakers, running shoes, jogging shoes, gym sports, work out, exercise shoes, fabric sneakers, stretchy sneakers, training, flexible, fitness, mesh flats. Size: Please read the size details in the left image before purchase. The colour maybe different from the picture shown due to the different screen of display or reflecting light when shooting. Best for Gifts: The perfect gift to share with your families, girlfriend/friends on birthdays, Holiday, Halloween, Teacher's Day, Mother's Day, Thanksgiving Day, and Christmas day etc.Unique Design: A variety of colorful prints and Personalized patterns, Please click on our store to find more different styles.","https://www.amazon.com/dp/B0C6V43KZ9?language=en_US&ref_=cm_sw_r_mwn_dp_PW6RXQJ67MJRMF5122VT"));
        mList.add(new PopularDomain(6,"NIKE Mens Full Force LoRunning Shoe", R.drawable.shoess_6_1, R.drawable.shoess_6_2, R.drawable.shoess_6_3, (int) 3.8,8,6724,"NIKE FULL FORCE LO-WHITE/MYSTIC RED-BLACK-SAIL-FB1362-102-7UK","https://www.amazon.in/dp/B0CLYVZMNZ?starsLeft=1&ref_=cm_sw_r_ud_dp_ASNF7F2D38MPMRRR4AHK"));

        //List of Spectacles.
        mList.add(new PopularDomain(11,"Toughened Glass Lens", R.drawable.spects_1_1, R.drawable.spects_1_2, R.drawable.spects_1_3,0,8,1280,"Top of Form ,Currently one of the most iconic sunglass models in the world. This style of sunglasses is credited with being one of the first popularized style of sunglasses to be developed. In its military usage, the sunglasses replaced the outmoded flight goggles used previously, as they were lighter, thinner, and more elegantly designed. Aviate Classic sunglasses are a timeless model that combines great aviator styling with exceptional quality, performance and comfort. With a classic metal frame, you can see the world through a variety of lens colors including dark, gradient, mercury and day and night that provide optimum visual clarity and 100% UV protection.","https://www.flipkart.com/r-resist-aviator-sunglasses/p/itm8714c5ba8a2f7?pid=SGLGB57VKREAZ2CD&cmpid=product.share.pp&_refId=PP.56f6a20f-8a22-4954-b8ee-72160aad14e4.SGLGB57VKREAZ2CD&_appId=WA"));
        mList.add(new PopularDomain(12,"Ray-Ban Men's Square Sunglasses", R.drawable.spects_2_1, R.drawable.spects_2_2, R.drawable.spects_2_3, (int) 4.1,7903,10429,"RAY-BAN | 0RB4165622/2V55 | Black | Square Sunglasses Lens Width :: 53.9 mm, Bridge Width :: 16 mm, Temple Length :: 145 mm","https://www.amazon.in/dp/B015EJWFZE?ref_=cm_sw_r_mwn_dp_9RBZACR5SD7GZE79K9ZF&language=en-IN"));
        mList.add(new PopularDomain(13,"Ray-Ban Rb3447 Round Metal Sunglasses", R.drawable.spects_3_1, R.drawable.spects_3_2, R.drawable.spects_3_3, (int) 4.1,103,0,"Timeless Ray-Ban Round sunglasses feature retro round metal frames, a look worn by legendary musicians and inspired by 1960s counter-culture Round shape, matte gold metal frame, fixed crystal green polarized lenses that make these frames look real Featuring an iconic G-15 lens engineered to give you the clearest and most natural vision absorbing 85% of visible light and blocking most blue light, it delivers remarkable color contrast and visual clarity.","https://www.amazon.in/dp/B00UO05CY0?starsLeft=1&ref_=cm_sw_r_ud_dp_8E4FN75F8CGVDD2CQ7E4"));
        mList.add(new PopularDomain(14,"UV Protected Unisex Sunglasses", R.drawable.spects_4_1, R.drawable.spects_4_2, R.drawable.spects_4_3,5,1,348,"A perfect blend of highly durable modern day materials styled with pure craftsmanship and the trust of thousands of customers.","https://www.amazon.in/dp/B0C4FBCJWC?starsLeft=1&ref_=cm_sw_r_ud_dp_K4CZRY9CVC6JAWEXRZ72"));
        mList.add(new PopularDomain(15,"UV Protection Over-sized Sunglasses",R.drawable.spects_5_1, R.drawable.spects_5_2, R.drawable.spects_5_3,0,0,474,"Size" + "This product is sold as Medium by the Brand" + "Ideal For" + "Men & Women" + "Purpose" + "Eye Protection" + "Lens Color and Material" + "Blue, Polycarbonate" + "Features" + "UV Protection" + "Frame Color" + "SILVER" + "Type" + "Over-sized" + "Style Code" + "RD-302-C1.","https://www.flipkart.com/roadies-over-sized-sunglasses/p/itm64baf95355cf8?pid=SGLGCQXV4VHFYJU6&cmpid=product.share.pp&_refId=PP.bb17b692-b946-4e7d-bfc3-b36da09e6fe9.SGLGCQXV4VHFYJU6&_appId=WA"));
        mList.add(new PopularDomain(16,"John Jacobs Brown Browline Polarized and UV Protected Sunglasses", R.drawable.spects_6_1, R.drawable.spects_6_2, R.drawable.spects_6_3, (int) 4.1,6,2639,"Material Composition UV protected Tortoise Golden Brown Solid Full Rim Browline John Jacobs JJ Tints JJ S13088-C2 Sunglasses" + "Polarized and 100% UV Protection (UV 400), Anti-Glare, Anti-Refraction" + "Ideal For Men & Women | Size: Large" + "Frame Material: Stainless Steel | Lens Material: Polycarbonate","https://www.amazon.in/dp/B08YNRMZG7?starsLeft=1&ref_=cm_sw_r_ud_dp_3X17N14C1KJJX775HYGW"));
        mList.add(new PopularDomain(17,"UV Protection Aviator Sunglasses",R.drawable.spects_7_1, R.drawable.spects_7_2, R.drawable.spects_7_3,0,0,1499,"Size " + "This product is sold as Small by the Brand " + "Ideal For " + "Men " + "Purpose " + "Running " + "Lens Color and Material " + "Black, Plastic " + "Features " + "UV Protection " + "Frame Color " + "Silver " + "Model Name " + "Velocity Full Rim Aviator Shape Sunglass " + "Type " + "Aviator","https://www.flipkart.com/speksee-aviator-sunglasses/p/itm578b54233f383?pid=SGLGUE8U4ABQVH5Y&cmpid=product.share.pp&_refId=PP.306a0ee9-796a-457d-a55a-aee80e38ff9f.SGLGUE8U4ABQVH5Y&_appId=WA"));
        mList.add(new PopularDomain(18,"Fastrack Mirrored Aviator Men's Sunglasses", R.drawable.spects_8_1, R.drawable.spects_8_2, R.drawable.spects_8_3, (int) 2.3,2,2295,"Size Map: Small " + "Frame size: Lens width - 55 mm, nose-bridge: 19 mm, temple length: 144 mm " + "1 year on manufacturing defects " + "100% UV protected " + "Black colored frame with Black temple " + "Metal frame","https://www.amazon.in/dp/B072B86W8D?starsLeft=1&ref_=cm_sw_r_ud_dp_25M4E28NEQ5H7ZS5AKN8"));
        mList.add(new PopularDomain(19,"UV Protection Cat-eye Sunglasses", R.drawable.spects_9_1, R.drawable.spects_9_2, R.drawable.spects_9_3,0,22,404, "Size " + "This product is sold as Free Size by the Brand " + "Ideal For " + "Women " + "Purpose " + "Style, Driving, Biking " + "Lens Color and Material " + "Silver, TAC Resin " + "Features " + "UV Protection " + "Frame Color " + "Golden " + "Type " + "Cat-eye " + "Style Code " + "Cat Eye Sunglasses for Women, Metal Frame Mirrored Lenses Fashion Sunglass","https://www.flipkart.com/jubilant-cat-eye-sunglasses/p/itm3de4bc213dbfa?pid=SGLG4GASS8MGUYHA&cmpid=product.share.pp&_refId=PP.1e1c2780-ba16-4b2d-8028-feade848aaca.SGLG4GASS8MGUYHA&_appId=WA"));
        mList.add(new PopularDomain(20,"Riding Glasses Wayfarer Sunglasses", R.drawable.spects_10_1, R.drawable.spects_10_2, R.drawable.spects_10_3,0,0,163, "The amazing accessories to enhance your style statement is Spectacles Frames. They are trendy and never really go out of style. Made of polycarbonate material our products are ergonomically designed to give you a comfortable head hugging fit. Thus providing all-day wearing comfort. Spectacles Frames have been designed keeping your comfort and care as our first priority. These Spectacles Frames are really light and have been made of high quality frame with Stunning Looks & Flashy Colors. Mehjabeen enterprise Frames give you 100% protection against harmful UVA/UVB rays and are polarized for your eye care. Stay young. What do You get? Sunglasses * 1 Sunglasses Case * 1 Cleaning Soft Cloth * 1 sunglasses for mens sunglasses for women stylish sunglasses for women sunglasses for men.","https://www.flipkart.com/mehj-wayfarer-sunglasses/p/itm2cce43ba560ac?pid=SGLGREWQMDHCP66F&cmpid=product.share.pp&_refId=PP.381b1f8c-8b1a-41ce-8dcd-24c783564627.SGLGREWQMDHCP66F&_appId=WA"));

        //List of Lipsticks.
        mList.add(new PopularDomain(21, "Maybelline Color Sensational Lipstick Pink Thrill",  R.drawable.lips_1_1, R.drawable.lips_1_2, R.drawable.lips_1_3, (int) 4.1, 34058, 1294, "Color Sensational The Creams delivers crisp color and smooth lips - Infused with Shea Butter, Color Sensational The Creams takes on a new feeling from the first touch of the packaging to the first swipe Color Sensational The Creams lipsticks deliver pure color pigments and Shea Butter for vibrant color, smooth lips and a creamy finish that does not bleed or feather Highly pigmented lip color with a creamy smooth glide during application that leaves lips feeling hydrated, nurtured, and conditioned Available in sensational lipstick shades you know and love - nudes, pinks, reds and plums - that are rich, warm and made to flatter your skin tone Color Sensational The Creams lipsticks now include your favorite shades from the Vivids and Buffs collections.", "https://www.amazon.in/Maybelline-Sensational-Lipstick-Hydrating-Packaging/dp/B07YXG7LSR"));
        mList.add(new PopularDomain(22, "Maybelline New York Color Sensational Creamy Matte Lipstick",  R.drawable.lips_2_1, R.drawable.lips_2_2, R.drawable.lips_2_3, (int) 4.1, 34058, 3937, "The Maybelline Color Sensational Creamy Mattes Lipstick has a unique, velvety matte cream formula that offers a non-drying & un-crackable finish that stays comfortably on your lips through the day These hydrating Maybelline lipstick shades are are infused with honey nectar to keep your lips moisturized all day long. The Colour Sensation lipsticks glide on your lips smoothly for a comfortable wear.The Color Sensational Creamy Matte Lipsticks are available in 30+ pigmented shades, from subtle nudes to bold reds and everything in between.Pair the Color Sensational Creamy Matte Lipstick with a nourishing Maybelline Lip Balm for colour and care!", "https://www.amazon.in/Maybelline-Sensational-Powder-Lipstick-Cherry/dp/B00N6MLLGG/ref=sr_1_1?crid=3IJQG46I8MI21&dib=eyJ2IjoiMSJ9.EFdP8swZrfqj1rSA6vUBbgTio0AzFqaG-afhFu2-nZGUDSrPAyWO5gORT2v_2blRhseMA4MuhZsOv4bMFt6vnUsXOKLVL4I2Z9ANvacTu5WwZPDmD3U4w_38DKFOtzGAYiauL2KBWxd9BIBpA9nyApPqV-Eh65itowxYje1f7lSuMq4xiDL0maeQhy2EICUCyOB3O2JjYmOFGojyT-05yYSW5oOMxVHosT8ZeRYZ-ao6uVADmOramKq2pdiaadyle8dreZMYP9OzCfwenJogbktEOxEkRYP_QkfRd7YnTag.BDVTqPI6NLrd7_Tg4gxj4rm55UaxnApJumK4sm8_oTY&dib_tag=se&keywords=yellow%2Bcolor%2Blipstick%2Bmaybelline&qid=1709892219&s=beauty&sprefix=yellow%2Bcolor%2Blipstick%2Bmabellin%2Cbeauty%2C336&sr=1-1&th=1"));
        mList.add(new PopularDomain(23, "Maybelline Color Sensational Lipstick Coral Rise", R.drawable.lips_3_1, R.drawable.lips_3_2, R.drawable.lips_3_3, (int) 4.1, 34058, 1668, "Color Sensational The Creams delivers crisp color and smooth lips - Infused with Shea Butter, Color Sensational The Creams takes on a new feeling from the first touch of the packaging to the first swipe Color Sensational The Creams lipsticks deliver pure color pigments and Shea Butter for vibrant color, smooth lips and a creamy finish that does not bleed or feather Highly pigmented lip color with a creamy smooth glide during application that leaves lips feeling hydrated, nurtured, and conditioned Available in sensational lipstick shades you know and love - nudes, pinks, reds and plums - that are rich, warm and made to flatter your skin tone Color Sensational The Creams lipsticks now include your favorite shades from the Vivids and Buffs collections.", "https://www.amazon.in/Maybelline-Sensational-Powder-Lipstick-Cherry/dp/B07YXG7LSV/ref=sr_1_1?crid=3IJQG46I8MI21&dib=eyJ2IjoiMSJ9.EFdP8swZrfqj1rSA6vUBbgTio0AzFqaG-afhFu2-nZGUDSrPAyWO5gORT2v_2blRhseMA4MuhZsOv4bMFt6vnUsXOKLVL4I2Z9ANvacTu5WwZPDmD3U4w_38DKFOtzGAYiauL2KBWxd9BIBpA9nyApPqV-Eh65itowxYje1f7lSuMq4xiDL0maeQhy2EICUCyOB3O2JjYmOFGojyT-05yYSW5oOMxVHosT8ZeRYZ-ao6uVADmOramKq2pdiaadyle8dreZMYP9OzCfwenJogbktEOxEkRYP_QkfRd7YnTag.BDVTqPI6NLrd7_Tg4gxj4rm55UaxnApJumK4sm8_oTY&dib_tag=se&keywords=yellow%2Bcolor%2Blipstick%2Bmaybelline&qid=1709892219&s=beauty&sprefix=yellow%2Bcolor%2Blipstick%2Bmabellin%2Cbeauty%2C336&sr=1-1&th=1"));
        mList.add(new PopularDomain(24, "Maybelline Color Sensational Lipstick Crimson Race", R.drawable.lips_4_1, R.drawable.lips_4_2, R.drawable.lips_4_3, (int) 4.1, 34058, 1338, "Color Sensational The Creams delivers crisp color and smooth lips - Infused with Shea Butter, Color Sensational The Creams takes on a new feeling from the first touch of the packaging to the first swipe Color Sensational The Creams lipsticks deliver pure color pigments and Shea Butter for vibrant color, smooth lips and a creamy finish that does not bleed or feather Highly pigmented lip color with a creamy smooth glide during application that leaves lips feeling hydrated, nurtured, and conditioned Available in sensational lipstick shades you know and love - nudes, pinks, reds and plums - that are rich, warm and made to flatter your skin tone Color Sensational The Creams lipsticks now include your favorite shades from the Vivids and Buffs collections.", "https://www.amazon.in/Maybelline-Sensational-Powder-Lipstick-Cherry/dp/B07YXG19S3/ref=sr_1_1?crid=3IJQG46I8MI21&dib=eyJ2IjoiMSJ9.EFdP8swZrfqj1rSA6vUBbgTio0AzFqaG-afhFu2-nZGUDSrPAyWO5gORT2v_2blRhseMA4MuhZsOv4bMFt6vnUsXOKLVL4I2Z9ANvacTu5WwZPDmD3U4w_38DKFOtzGAYiauL2KBWxd9BIBpA9nyApPqV-Eh65itowxYje1f7lSuMq4xiDL0maeQhy2EICUCyOB3O2JjYmOFGojyT-05yYSW5oOMxVHosT8ZeRYZ-ao6uVADmOramKq2pdiaadyle8dreZMYP9OzCfwenJogbktEOxEkRYP_QkfRd7YnTag.BDVTqPI6NLrd7_Tg4gxj4rm55UaxnApJumK4sm8_oTY&dib_tag=se&keywords=yellow%2Bcolor%2Blipstick%2Bmaybelline&qid=1709892219&s=beauty&sprefix=yellow%2Bcolor%2Blipstick%2Bmabellin%2Cbeauty%2C336&sr=1-1&th=1"));
        mList.add(new PopularDomain(25, "Maybelline Color Sensational Lipstick Bare Reveal", R.drawable.lips_5_1, R.drawable.lips_5_2, R.drawable.lips_5_3, (int) 4.1, 34058, 1820, "Color Sensational The Creams delivers crisp color and smooth lips - Infused with Shea Butter, Color Sensational The Creams takes on a new feeling from the first touch of the packaging to the first swipe Color Sensational The Creams lipsticks deliver pure color pigments and Shea Butter for vibrant color, smooth lips and a creamy finish that does not bleed or feather Highly pigmented lip color with a creamy smooth glide during application that leaves lips feeling hydrated, nurtured, and conditioned Available in sensational lipstick shades you know and love - nudes, pinks, reds and plums - that are rich, warm and made to flatter your skin tone Color Sensational The Creams lipsticks now include your favorite shades from the Vivids and Buffs collections.", "https://www.amazon.in/Maybelline-Sensational-Powder-Lipstick-Cherry/dp/B07YXFYM3Z/ref=sr_1_1?crid=3IJQG46I8MI21&dib=eyJ2IjoiMSJ9.EFdP8swZrfqj1rSA6vUBbgTio0AzFqaG-afhFu2-nZGUDSrPAyWO5gORT2v_2blRhseMA4MuhZsOv4bMFt6vnUsXOKLVL4I2Z9ANvacTu5WwZPDmD3U4w_38DKFOtzGAYiauL2KBWxd9BIBpA9nyApPqV-Eh65itowxYje1f7lSuMq4xiDL0maeQhy2EICUCyOB3O2JjYmOFGojyT-05yYSW5oOMxVHosT8ZeRYZ-ao6uVADmOramKq2pdiaadyle8dreZMYP9OzCfwenJogbktEOxEkRYP_QkfRd7YnTag.BDVTqPI6NLrd7_Tg4gxj4rm55UaxnApJumK4sm8_oTY&dib_tag=se&keywords=yellow%2Bcolor%2Blipstick%2Bmaybelline&qid=1709892219&s=beauty&sprefix=yellow%2Bcolor%2Blipstick%2Bmabellin%2Cbeauty%2C336&sr=1-1&th=1"));
        mList.add(new PopularDomain(26, "Maybelline Color Sensational Lipstick Naked Dare",  R.drawable.lips_6_1, R.drawable.lips_6_2, R.drawable.lips_6_3, (int) 4.1, 34058, 1509, "Color Sensational The Creams delivers crisp color and smooth lips - Infused with Shea Butter, Color Sensational The Creams takes on a new feeling from the first touch of the packaging to the first swipe Color Sensational The Creams lipsticks deliver pure color pigments and Shea Butter for vibrant color, smooth lips and a creamy finish that does not bleed or feather Highly pigmented lip color with a creamy smooth glide during application that leaves lips feeling hydrated, nurtured, and conditioned Available in sensational lipstick shades you know and love - nudes, pinks, reds and plums - that are rich, warm and made to flatter your skin tone Color Sensational The Creams lipsticks now include your favorite shades from the Vivids and Buffs collections.", "https://www.amazon.in/Maybelline-Sensational-Powder-Lipstick-Cherry/dp/B07YXGG4D1/ref=sr_1_1?crid=3IJQG46I8MI21&dib=eyJ2IjoiMSJ9.EFdP8swZrfqj1rSA6vUBbgTio0AzFqaG-afhFu2-nZGUDSrPAyWO5gORT2v_2blRhseMA4MuhZsOv4bMFt6vnUsXOKLVL4I2Z9ANvacTu5WwZPDmD3U4w_38DKFOtzGAYiauL2KBWxd9BIBpA9nyApPqV-Eh65itowxYje1f7lSuMq4xiDL0maeQhy2EICUCyOB3O2JjYmOFGojyT-05yYSW5oOMxVHosT8ZeRYZ-ao6uVADmOramKq2pdiaadyle8dreZMYP9OzCfwenJogbktEOxEkRYP_QkfRd7YnTag.BDVTqPI6NLrd7_Tg4gxj4rm55UaxnApJumK4sm8_oTY&dib_tag=se&keywords=yellow%2Bcolor%2Blipstick%2Bmaybelline&qid=1709892219&s=beauty&sprefix=yellow%2Bcolor%2Blipstick%2Bmabellin%2Cbeauty%2C336&sr=1-1&th=1"));
        mList.add(new PopularDomain(27, "Maybelline Color Sensational Matte Lipstick",  R.drawable.lips_7_1, R.drawable.lips_7_2, R.drawable.lips_7_3, (int) 4.1, 34058, 1220, "Color Sensational The Creams delivers crisp color and smooth lips - Infused with Shea Butter, Color Sensational The Creams takes on a new feeling from the first touch of the packaging to the first swipe Color Sensational The Creams lipsticks deliver pure color pigments and Shea Butter for vibrant color, smooth lips and a creamy finish that does not bleed or feather Highly pigmented lip color with a creamy smooth glide during application that leaves lips feeling hydrated, nurtured, and conditioned Available in sensational lipstick shades you know and love - nudes, pinks, reds and plums - that are rich, warm and made to flatter your skin tone Color Sensational The Creams lipsticks now include your favorite shades from the Vivids and Buffs collections.", "https://www.amazon.in/Maybelline-Sensational-Powder-Lipstick-Cherry/dp/B01DPA81IE/ref=sr_1_1?crid=3IJQG46I8MI21&dib=eyJ2IjoiMSJ9.EFdP8swZrfqj1rSA6vUBbgTio0AzFqaG-afhFu2-nZGUDSrPAyWO5gORT2v_2blRhseMA4MuhZsOv4bMFt6vnUsXOKLVL4I2Z9ANvacTu5WwZPDmD3U4w_38DKFOtzGAYiauL2KBWxd9BIBpA9nyApPqV-Eh65itowxYje1f7lSuMq4xiDL0maeQhy2EICUCyOB3O2JjYmOFGojyT-05yYSW5oOMxVHosT8ZeRYZ-ao6uVADmOramKq2pdiaadyle8dreZMYP9OzCfwenJogbktEOxEkRYP_QkfRd7YnTag.BDVTqPI6NLrd7_Tg4gxj4rm55UaxnApJumK4sm8_oTY&dib_tag=se&keywords=yellow%2Bcolor%2Blipstick%2Bmaybelline&qid=1709892219&s=beauty&sprefix=yellow%2Bcolor%2Blipstick%2Bmabellin%2Cbeauty%2C336&sr=1-1&th=1"));
        mList.add(new PopularDomain(28, "Maybelline New York Color Sensational Rebel Bloom Lipstick",  R.drawable.lips_8_1, R.drawable.lips_8_2, R.drawable.lips_8_3, (int) 4.1, 34058, 8011, "MATTE FINISH MAYBELLINE LIPSTICK: This velvety, hydrating matte lipstick goes on in one swipe, delivering bold, intense color that lasts. Formulated with honey nectar for a sensuous finish.COLOR SENSATIONAL LIPSTICK: For hyperpigmented lip color in an ultra-hydrating formula, look no further than Color Sensational lipsticks. Available in matte, satin, & gloss & shades from nude to bold black.MAYBELLINE LIPS: Layer on intense color that lasts with Superstay 24 hr Lip color, slay a matte lip with SuperStay Matte Ink Liquid Lipstick, renew with Baby Lips Moisturizing Lip Balm, or add gloss to any color with Clear Lip Gloss Topcoat.MAYBELLINE HAS WHAT YOU NEED to create any look—foundation, bb creams, concealers, & highlighters for the perfect canvas, eyeshadows, brow pencils, & eyeliners for any eye look & lip products, from showstopping matte lipstick to au natural lip balms. REMOVE MAYBELLINE MAKEUP WITH MICELLAR WATER: Use Garnier Micellar Water as a gentle makeup remover at night, & as a facial cleanser in the morning to prep skin for Maybelline makeup.", "https://www.amazon.in/Maybelline-Sensational-Powder-Lipstick-Cherry/dp/B00PFCS5L4/ref=sr_1_1?crid=3IJQG46I8MI21&dib=eyJ2IjoiMSJ9.EFdP8swZrfqj1rSA6vUBbgTio0AzFqaG-afhFu2-nZGUDSrPAyWO5gORT2v_2blRhseMA4MuhZsOv4bMFt6vnUsXOKLVL4I2Z9ANvacTu5WwZPDmD3U4w_38DKFOtzGAYiauL2KBWxd9BIBpA9nyApPqV-Eh65itowxYje1f7lSuMq4xiDL0maeQhy2EICUCyOB3O2JjYmOFGojyT-05yYSW5oOMxVHosT8ZeRYZ-ao6uVADmOramKq2pdiaadyle8dreZMYP9OzCfwenJogbktEOxEkRYP_QkfRd7YnTag.BDVTqPI6NLrd7_Tg4gxj4rm55UaxnApJumK4sm8_oTY&dib_tag=se&keywords=yellow%2Bcolor%2Blipstick%2Bmaybelline&qid=1709892219&s=beauty&sprefix=yellow%2Bcolor%2Blipstick%2Bmabellin%2Cbeauty%2C336&sr=1-1&th=1"));
        mList.add(new PopularDomain(29, "Maybelline New York Color Sensational Creamy Matte Lipstick", R.drawable.lips_9_1, R.drawable.lips_9_2, R.drawable.lips_9_3, (int) 4.1, 34058, 1842, "Super-saturated pigments take fresh picked pastels to a new bright Never dull, washed out or shy Honey nectar adds a sumptuous feel This Product is Shipped from USA within 7 to 14 days of reciept of order.", "https://www.amazon.in/Maybelline-Sensational-Powder-Lipstick-Cherry/dp/B00YJJWLLE/ref=sr_1_1?crid=3IJQG46I8MI21&dib=eyJ2IjoiMSJ9.EFdP8swZrfqj1rSA6vUBbgTio0AzFqaG-afhFu2-nZGUDSrPAyWO5gORT2v_2blRhseMA4MuhZsOv4bMFt6vnUsXOKLVL4I2Z9ANvacTu5WwZPDmD3U4w_38DKFOtzGAYiauL2KBWxd9BIBpA9nyApPqV-Eh65itowxYje1f7lSuMq4xiDL0maeQhy2EICUCyOB3O2JjYmOFGojyT-05yYSW5oOMxVHosT8ZeRYZ-ao6uVADmOramKq2pdiaadyle8dreZMYP9OzCfwenJogbktEOxEkRYP_QkfRd7YnTag.BDVTqPI6NLrd7_Tg4gxj4rm55UaxnApJumK4sm8_oTY&dib_tag=se&keywords=yellow%2Bcolor%2Blipstick%2Bmaybelline&qid=1709892219&s=beauty&sprefix=yellow%2Bcolor%2Blipstick%2Bmabellin%2Cbeauty%2C336&sr=1-1&th=1"));
        mList.add(new PopularDomain(30, "Maybelline New York Color Sensational Rebel Bloom Lipstick -Power Peony", R.drawable.lips_10_1, R.drawable.lips_10_2, R.drawable.lips_10_3, (int) 4.1, 34058, 2787, "The Maybelline Color Sensational Creamy Mattes Lipstick has a unique, velvety matte cream formula that offers a non-drying & un-crackable finish that stays comfortably on your lips through the day These hydrating Maybelline lipstick shades are are infused with honey nectar to keep your lips moisturized all day long. The Colour Sensation lipsticks glide on your lips smoothly for a comfortable wear.The Color Sensational Creamy Matte Lipsticks are available in 30+ pigmented shades, from subtle nudes to bold reds and everything in between.Pair the Color Sensational Creamy Matte Lipstick with a nourishing Maybelline Lip Balm for colour and care!", "https://www.amazon.in/Maybelline-Sensational-Powder-Lipstick-Cherry/dp/B00PFCS5QY/ref=sr_1_1?crid=3IJQG46I8MI21&dib=eyJ2IjoiMSJ9.EFdP8swZrfqj1rSA6vUBbgTio0AzFqaG-afhFu2-nZGUDSrPAyWO5gORT2v_2blRhseMA4MuhZsOv4bMFt6vnUsXOKLVL4I2Z9ANvacTu5WwZPDmD3U4w_38DKFOtzGAYiauL2KBWxd9BIBpA9nyApPqV-Eh65itowxYje1f7lSuMq4xiDL0maeQhy2EICUCyOB3O2JjYmOFGojyT-05yYSW5oOMxVHosT8ZeRYZ-ao6uVADmOramKq2pdiaadyle8dreZMYP9OzCfwenJogbktEOxEkRYP_QkfRd7YnTag.BDVTqPI6NLrd7_Tg4gxj4rm55UaxnApJumK4sm8_oTY&dib_tag=se&keywords=yellow%2Bcolor%2Blipstick%2Bmaybelline&qid=1709892219&s=beauty&sprefix=yellow%2Bcolor%2Blipstick%2Bmabellin%2Cbeauty%2C336&sr=1-1&th=1"));

        //List of Eyelashes.
        mList.add(new PopularDomain(31,"MARS Fabulash Eyelashes (Spice Art)", R.drawable.eyels_1_1, R.drawable.eyels_1_2, R.drawable.eyels_1_3, (int) 3.9,26,95,"Lashes Can be used for upto 10 times, If proper care is taken, Make Sure you clean the Band after every use and Store them Properly in the Box Provided They are a mix of natural and heavy lashes You can wear them everyday or in parties.These lashes have a thin band.","https://www.amazon.in/dp/B0BD8CWBST?ref_=cm_sw_r_mwn_dp_GYAVWZND92Y6Y7ETQ433&language=en_US"));
        mList.add(new PopularDomain(32,"MARS Fabulash Eyelashes (Party Ready)", R.drawable.eyels_2_1, R.drawable.eyels_2_2, R.drawable.eyels_2_3, (int) 3.9,26,95,"Lashes Can be used for upto 10 times, If proper care is taken, Make Sure you clean the Band after every use and Store them Properly in the Box Provided They are a mix of natural and heavy lashes You can wear them everyday or in parties.These lashes have a thin band.They have synthetic hair.","https://www.amazon.in/dp/B0BD8DX6WQ?ref_=cm_sw_r_mwn_dp_GYAVWZND92Y6Y7ETQ433&language=en_US&th=1"));
        mList.add(new PopularDomain(33,"MARS Fabulash Eyelashes (Glam On)", R.drawable.eyels_3_1, R.drawable.eyels_3_2, R.drawable.eyels_3_3, (int) 3.9,26,95,"Lashes Can be used for upto 10 times, If proper care is taken, Make Sure you clean the Band after every use and Store them Properly in the Box Provided They are a mix of natural and heavy lashes You can wear them everyday or in parties.These lashes have a thin band.They have synthetic hair.","https://www.amazon.in/dp/B0BD8FZ4GY?ref_=cm_sw_r_mwn_dp_GYAVWZND92Y6Y7ETQ433&language=en_US&th=1"));
        mList.add(new PopularDomain(34,"MARS Fabulash Eyelashes (Drag Queen)", R.drawable.eyels_4_1, R.drawable.eyels_4_2, R.drawable.eyels_4_3, (int) 3.9,26,95,"Lashes Can be used for upto 10 times, If proper care is taken, Make Sure you clean the Band after every use and Store them Properly in the Box Provided They are a mix of natural and heavy lashes You can wear them everyday or in parties.These lashes have a thin band.They have synthetic hair.","https://www.amazon.in/dp/B0BD8FRL83?ref_=cm_sw_r_mwn_dp_GYAVWZND92Y6Y7ETQ433&language=en_US&th=1"));
        mList.add(new PopularDomain(35,"MARS Fabulash Eyelashes (Flirty Miss)", R.drawable.eyels_5_1, R.drawable.eyels_5_2, R.drawable.eyels_5_3, (int) 3.9,26,95,"Lashes Can be used for upto 10 times, If proper care is taken, Make Sure you clean the Band after every use and Store them Properly in the Box Provided They are a mix of natural and heavy lashes You can wear them everyday or in parties.These lashes have a thin band.They have synthetic hair.","https://www.amazon.in/dp/B0BD8HD2SP?ref_=cm_sw_r_mwn_dp_GYAVWZND92Y6Y7ETQ433&language=en_US&th=1"));
        mList.add(new PopularDomain(36,"MARS Fabulash Eyelashes (OG Princess)", R.drawable.eyels_6_1, R.drawable.eyels_6_2, R.drawable.eyels_6_3, (int) 3.9,26,95,"Lashes Can be used for upto 10 times, If proper care is taken, Make Sure you clean the Band after every use and Store them Properly in the Box Provided They are a mix of natural and heavy lashes You can wear them everyday or in parties.These lashes have a thin band.","https://www.amazon.in/dp/B0BD8H6957?ref_=cm_sw_r_mwn_dp_GYAVWZND92Y6Y7ETQ433&language=en_US&th=1"));
        mList.add(new PopularDomain(37,"MARS Fabulash Eyelashes (Over The Top)", R.drawable.eyels_7_1, R.drawable.eyels_7_2, R.drawable.eyels_7_3, (int) 3.9,26,95,"Lashes Can be used for upto 10 times, If proper care is taken, Make Sure you clean the Band after every use and Store them Properly in the Box Provided They are a mix of natural and heavy lashes You can wear them everyday or in parties.These lashes have a thin band.They have synthetic hair.","https://www.amazon.in/dp/B0BD8H26J5?ref_=cm_sw_r_mwn_dp_GYAVWZND92Y6Y7ETQ433&language=en_US&th=1"));
        mList.add(new PopularDomain(38,"MARS Fabulash Eyelashes (Natural Flutter)", R.drawable.eyels_8_1, R.drawable.eyels_8_2, R.drawable.eyels_8_3, (int) 3.9,26,95,"Lashes Can be used for upto 10 times, If proper care is taken, Make Sure you clean the Band after every use and Store them Properly in the Box Provided They are a mix of natural and heavy lashes You can wear them everyday or in parties.These lashes have a thin band.","https://www.amazon.in/dp/B0BD8HTQZZ?ref_=cm_sw_r_mwn_dp_GYAVWZND92Y6Y7ETQ433&language=en_US&th=1"));
        mList.add(new PopularDomain(39,"3D Faux Mink Fake Eyelash Long Natural - 63", R.drawable.eyels_9_1, R.drawable.eyels_9_2, R.drawable.eyels_9_3, (int) 3.9,58,85,"The band of these false eyelashes is clear and super-fine. The lashes are lighter, more invisible, and more comfortable than lashes with a black band. Your eyes are not burdened by heavy eyelashes. It's recommended to pair it with the Bronson professional eyelash adhesive, which can last a long time and preserve the perfect impression.NATURAL LOOK- The fluffy false eyelashes that look very similar to real eyelashes and naturally enlarge your eyes. The naturally curled curvature and the right length effect give you a low-key look.","https://www.amazon.in/False-Eyelash-Makeup-Natural-Eyelashes/dp/B0BPJTRDHS/ref=sr_1_33?crid=2IWE2QRTDMTAR&dib=eyJ2IjoiMSJ9.6D-5LC5upZWHsqpODEaEPkRItwGGJpAdpQjkr3S0yBFOfXvbJkzsaBLmzOj7SLvlGM0trVD784GlHfJf9IyKxt2lA4KpWz10sX1gP0fAtG4hyhffZXmIpx9p7jCESw_mle8wQ9-o7c9mbkSde0r6MBtoJEcNcsypIM-0EsNzRDqdUVa2R3qvPtmlNX3pURGvg19XbvyaanVGS7M8UE8W5UwjkLkFjkNE_72dKa3VkqEeTOzuc4cIdNbpcP9e4qjIto-akVtXGFUVkmkFH_R9vK0XF4EViA0e16qdvUGS7Lc.BT8M4tYFCedtqNifsGwQV8vaiCrMs9t0sShYZJJeHGg&dib_tag=se&keywords=eyelashes%2Bsmall%2Bsize%2Bsingle&qid=1709916311&s=beauty&sprefix=eyelashes%2Bsmall%2Bsize%2Bsingle%2Cbeauty%2C385&sr=1-33&th=1"));
        mList.add(new PopularDomain(40,"3D Faux Mink Fake Eyelash Long Natural - 53", R.drawable.eyels_10_1, R.drawable.eyels_10_2, R.drawable.eyels_10_3, (int) 3.9,58,85,"The band of these false eyelashes is clear and super-fine. The lashes are lighter, more invisible, and more comfortable than lashes with a black band. Your eyes are not burdened by heavy eyelashes. It's recommended to pair it with the Bronson professional eyelash adhesive, which can last a long time and preserve the perfect impression.NATURAL LOOK- The fluffy false eyelashes that look very similar to real eyelashes and naturally enlarge your eyes. The naturally curled curvature and the right length effect give you a low-key look.","https://www.amazon.in/False-Eyelash-Makeup-Natural-Eyelashes/dp/B0BPJHWN1Y/ref=acm_sr_dp?crid=2IWE2QRTDMTAR&dib=eyJ2IjoiMSJ9.6D-5LC5upZWHsqpODEaEPkRItwGGJpAdpQjkr3S0yBFOfXvbJkzsaBLmzOj7SLvlGM0trVD784GlHfJf9IyKxt2lA4KpWz10sX1gP0fAtG4hyhffZXmIpx9p7jCESw_mle8wQ9-o7c9mbkSde0r6MBtoJEcNcsypIM-0EsNzRDqdUVa2R3qvPtmlNX3pURGvg19XbvyaanVGS7M8UE8W5UwjkLkFjkNE_72dKa3VkqEeTOzuc4cIdNbpcP9e4qjIto-akVtXGFUVkmkFH_R9vK0XF4EViA0e16qdvUGS7Lc.BT8M4tYFCedtqNifsGwQV8vaiCrMs9t0sShYZJJeHGg&dib_tag=se&keywords=eyelashes%2Bsmall%2Bsize%2Bsingle&qid=1709916311&s=beauty&sprefix=eyelashes%2Bsmall%2Bsize%2Bsingle%2Cbeauty%2C385&sr=1-33&th=1"));

        //List of EyeShadow.
        mList.add(new PopularDomain(41,"Miss Claire Single Eyeshadow - 0507", R.drawable.eyesh_1_1, R.drawable.eyesh_1_2, R.drawable.eyesh_1_3, (int) 4.2, 6963, 80,"Miss Claire's Single Eye Shadow features a long-wearing crème powder formula that is super creamy, insanely pigmented, and has one swipe intensity. This collection features a range of everyday shades that combine high-pigment with high-shine.","https://www.nykaa.com/miss-claire-single-eyeshadow/p/271315?ptype=product&skuId=271289&utm_content=ads&utm_source=GooglePaid&utm_medium=PLA&utm_campaign=PerformanceMaxFullSiteATC&hlp=hlpa&gad_source=4&gclid=CjwKCAiAi6uvBhADEiwAWiyRduHTobTp_9BBDvS_liGkNx7hCNsWYf-lJW-OAYqC4yPDOY6NSISjxBoCyEAQAvD_BwE"));
        mList.add(new PopularDomain(42,"Miss Claire Single Eyeshadow - 0753", R.drawable.eyesh_2_1, R.drawable.eyesh_2_2, R.drawable.eyesh_2_3, (int) 4.2, 6963, 80,"Miss Claire's Single Eye Shadow features a long-wearing crème powder formula that is super creamy, insanely pigmented, and has one swipe intensity. This collection features a range of everyday shades that combine high-pigment with high-shine.","https://www.nykaa.com/miss-claire-single-eyeshadow/p/271315?ptype=product&skuId=271299&utm_content=ads&utm_source=GooglePaid&utm_medium=PLA&utm_campaign=PerformanceMaxFullSiteATC&hlp=hlpa&gad_source=4&gclid=CjwKCAiAi6uvBhADEiwAWiyRduHTobTp_9BBDvS_liGkNx7hCNsWYf-lJW-OAYqC4yPDOY6NSISjxBoCyEAQAvD_BwE"));
        mList.add(new PopularDomain(43,"Miss Claire Single Eyeshadow - 0913", R.drawable.eyesh_3_1, R.drawable.eyesh_3_2, R.drawable.eyesh_3_3, (int) 4.2, 6963, 80,"Miss Claire's Single Eye Shadow features a long-wearing crème powder formula that is super creamy, insanely pigmented, and has one swipe intensity. This collection features a range of everyday shades that combine high-pigment with high-shine.","https://www.nykaa.com/miss-claire-single-eyeshadow/p/271315?ptype=product&skuId=271312&utm_content=ads&utm_source=GooglePaid&utm_medium=PLA&utm_campaign=PerformanceMaxFullSiteATC&hlp=hlpa&gad_source=4&gclid=CjwKCAiAi6uvBhADEiwAWiyRduHTobTp_9BBDvS_liGkNx7hCNsWYf-lJW-OAYqC4yPDOY6NSISjxBoCyEAQAvD_BwE"));
//        mList.add(new PopularDomain(44,"",R.drawable.eyesh_4_1,R.drawable.eyesh_4_2,R.drawable.eyesh_4_3, 4.2, 6963, 80,"Miss Claire's Single Eye Shadow features a long-wearing crème powder formula that is super creamy, insanely pigmented, and has one swipe intensity. This collection features a range of everyday shades that combine high-pigment with high-shine.",""));
        mList.add(new PopularDomain(45,"Miss Claire Single Eyeshadow - 0459", R.drawable.eyesh_5_1, R.drawable.eyesh_5_2, R.drawable.eyesh_5_3, (int) 4.2, 6963, 80,"Miss Claire's Single Eye Shadow features a long-wearing crème powder formula that is super creamy, insanely pigmented, and has one swipe intensity. This collection features a range of everyday shades that combine high-pigment with high-shine.","https://www.nykaa.com/miss-claire-single-eyeshadow/p/271315?ptype=product&skuId=271283&utm_content=ads&utm_source=GooglePaid&utm_medium=PLA&utm_campaign=PerformanceMaxFullSiteATC&hlp=hlpa&gad_source=4&gclid=CjwKCAiAi6uvBhADEiwAWiyRduHTobTp_9BBDvS_liGkNx7hCNsWYf-lJW-OAYqC4yPDOY6NSISjxBoCyEAQAvD_BwE"));
        mList.add(new PopularDomain(46,"Miss Claire Single Eyeshadow - 0456", R.drawable.eyesh_6_1, R.drawable.eyesh_6_2, R.drawable.eyesh_6_3, (int) 4.2, 6963, 80,"Miss Claire's Single Eye Shadow features a long-wearing crème powder formula that is super creamy, insanely pigmented, and has one swipe intensity. This collection features a range of everyday shades that combine high-pigment with high-shine.","https://www.nykaa.com/miss-claire-single-eyeshadow/p/271315?ptype=product&skuId=271280&utm_content=ads&utm_source=GooglePaid&utm_medium=PLA&utm_campaign=PerformanceMaxFullSiteATC&hlp=hlpa&gad_source=4&gclid=CjwKCAiAi6uvBhADEiwAWiyRduHTobTp_9BBDvS_liGkNx7hCNsWYf-lJW-OAYqC4yPDOY6NSISjxBoCyEAQAvD_BwE"));
        mList.add(new PopularDomain(47,"Miss Claire Single Eyeshadow - 0457", R.drawable.eyesh_7_1, R.drawable.eyesh_7_2, R.drawable.eyesh_7_3, (int) 4.2, 6963, 80,"Miss Claire's Single Eye Shadow features a long-wearing crème powder formula that is super creamy, insanely pigmented, and has one swipe intensity. This collection features a range of everyday shades that combine high-pigment with high-shine.","https://www.nykaa.com/miss-claire-single-eyeshadow/p/271315?ptype=product&skuId=271281&utm_content=ads&utm_source=GooglePaid&utm_medium=PLA&utm_campaign=PerformanceMaxFullSiteATC&hlp=hlpa&gad_source=4&gclid=CjwKCAiAi6uvBhADEiwAWiyRduHTobTp_9BBDvS_liGkNx7hCNsWYf-lJW-OAYqC4yPDOY6NSISjxBoCyEAQAvD_BwE"));
        mList.add(new PopularDomain(48,"Miss Claire Single Eyeshadow - 0250", R.drawable.eyesh_8_1, R.drawable.eyesh_8_2, R.drawable.eyesh_8_3, (int) 4.2, 6963, 80,"Miss Claire's Single Eye Shadow features a long-wearing crème powder formula that is super creamy, insanely pigmented, and has one swipe intensity. This collection features a range of everyday shades that combine high-pigment with high-shine.","https://www.nykaa.com/miss-claire-single-eyeshadow/p/271315?ptype=product&skuId=271277&utm_content=ads&utm_source=GooglePaid&utm_medium=PLA&utm_campaign=PerformanceMaxFullSiteATC&hlp=hlpa&gad_source=4&gclid=CjwKCAiAi6uvBhADEiwAWiyRduHTobTp_9BBDvS_liGkNx7hCNsWYf-lJW-OAYqC4yPDOY6NSISjxBoCyEAQAvD_BwE"));
        mList.add(new PopularDomain(49,"Miss Claire Single Eyeshadow - 0951", R.drawable.eyesh_9_1, R.drawable.eyesh_9_2, R.drawable.eyesh_9_3, (int) 4.2, 6963, 80,"Miss Claire's Single Eye Shadow features a long-wearing crème powder formula that is super creamy, insanely pigmented, and has one swipe intensity. This collection features a range of everyday shades that combine high-pigment with high-shine.","https://www.nykaa.com/miss-claire-single-eyeshadow/p/271315?ptype=product&skuId=271313&utm_content=ads&utm_source=GooglePaid&utm_medium=PLA&utm_campaign=PerformanceMaxFullSiteATC&hlp=hlpa&gad_source=4&gclid=CjwKCAiAi6uvBhADEiwAWiyRduHTobTp_9BBDvS_liGkNx7hCNsWYf-lJW-OAYqC4yPDOY6NSISjxBoCyEAQAvD_BwE"));
        mList.add(new PopularDomain(50,"Miss Claire Single Eyeshadow - 0457",R.drawable.eyesh_10_1, R.drawable.eyesh_10_1, R.drawable.eyesh_10_3, (int) 4.2, 6963, 80,"Miss Claire's Single Eye Shadow features a long-wearing crème powder formula that is super creamy, insanely pigmented, and has one swipe intensity. This collection features a range of everyday shades that combine high-pigment with high-shine.","https://www.nykaa.com/miss-claire-single-eyeshadow/p/271315?ptype=product&skuId=271281&utm_content=ads&utm_source=GooglePaid&utm_medium=PLA&utm_campaign=PerformanceMaxFullSiteATC&hlp=hlpa&gad_source=4&gclid=CjwKCAiAi6uvBhADEiwAWiyRduHTobTp_9BBDvS_liGkNx7hCNsWYf-lJW-OAYqC4yPDOY6NSISjxBoCyEAQAvD_BwE"));

    }
}
