package com.example.stylemirror_1_1.Activity;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;

import android.os.Bundle;

import com.example.stylemirror_1_1.Adapter.PopularAdapter;
import com.example.stylemirror_1_1.databinding.ActivityCosmeticsListBinding;
import com.example.stylemirror_1_1.domain.PopularDomain;

import java.util.ArrayList;

public class activity_cosmetics_list extends AppCompatActivity {

    ActivityCosmeticsListBinding binding;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = ActivityCosmeticsListBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());
        itemlistRecyclerView();
    }

    private void itemlistRecyclerView() {
        ArrayList<PopularDomain> items = new ArrayList<>();

        //List of Lipstick.
        items.add(new PopularDomain(21, "Maybelline Color Sensational Lipstick Pink Thrill", "lips_1_1", "lips_1_2", "lips_1_3", 4.1, 34058, 1248, "Color Sensational The Creams delivers crisp color and smooth lips - Infused with Shea Butter, Color Sensational The Creams takes on a new feeling from the first touch of the packaging to the first swipe Color Sensational The Creams lipsticks deliver pure color pigments and Shea Butter for vibrant color, smooth lips and a creamy finish that does not bleed or feather Highly pigmented lip color with a creamy smooth glide during application that leaves lips feeling hydrated, nurtured, and conditioned Available in sensational lipstick shades you know and love - nudes, pinks, reds and plums - that are rich, warm and made to flatter your skin tone Color Sensational The Creams lipsticks now include your favorite shades from the Vivids and Buffs collections.", "https://www.amazon.in/Maybelline-Sensational-Lipstick-Hydrating-Packaging/dp/B07YXG7LSR"));
        items.add(new PopularDomain(22, "Maybelline New York Color Sensational Creamy Matte Lipstick", "lips_2_1", "lips_2_2", "lips_2_3", 4.1, 34058, 3937, "The Maybelline Color Sensational Creamy Mattes Lipstick has a unique, velvety matte cream formula that offers a non-drying & un-crackable finish that stays comfortably on your lips through the day These hydrating Maybelline lipstick shades are are infused with honey nectar to keep your lips moisturized all day long. The Colour Sensation lipsticks glide on your lips smoothly for a comfortable wear.The Color Sensational Creamy Matte Lipsticks are available in 30+ pigmented shades, from subtle nudes to bold reds and everything in between.Pair the Color Sensational Creamy Matte Lipstick with a nourishing Maybelline Lip Balm for colour and care!", "https://www.amazon.in/Maybelline-Sensational-Powder-Lipstick-Cherry/dp/B00N6MLLGG/ref=sr_1_1?crid=3IJQG46I8MI21&dib=eyJ2IjoiMSJ9.EFdP8swZrfqj1rSA6vUBbgTio0AzFqaG-afhFu2-nZGUDSrPAyWO5gORT2v_2blRhseMA4MuhZsOv4bMFt6vnUsXOKLVL4I2Z9ANvacTu5WwZPDmD3U4w_38DKFOtzGAYiauL2KBWxd9BIBpA9nyApPqV-Eh65itowxYje1f7lSuMq4xiDL0maeQhy2EICUCyOB3O2JjYmOFGojyT-05yYSW5oOMxVHosT8ZeRYZ-ao6uVADmOramKq2pdiaadyle8dreZMYP9OzCfwenJogbktEOxEkRYP_QkfRd7YnTag.BDVTqPI6NLrd7_Tg4gxj4rm55UaxnApJumK4sm8_oTY&dib_tag=se&keywords=yellow%2Bcolor%2Blipstick%2Bmaybelline&qid=1709892219&s=beauty&sprefix=yellow%2Bcolor%2Blipstick%2Bmabellin%2Cbeauty%2C336&sr=1-1&th=1"));
        items.add(new PopularDomain(23, "Maybelline Color Sensational Lipstick Coral Rise", "lips_3_1", "lips_3_2", "lips_3_3", 4.1, 34058, 1693, "Color Sensational The Creams delivers crisp color and smooth lips - Infused with Shea Butter, Color Sensational The Creams takes on a new feeling from the first touch of the packaging to the first swipe Color Sensational The Creams lipsticks deliver pure color pigments and Shea Butter for vibrant color, smooth lips and a creamy finish that does not bleed or feather Highly pigmented lip color with a creamy smooth glide during application that leaves lips feeling hydrated, nurtured, and conditioned Available in sensational lipstick shades you know and love - nudes, pinks, reds and plums - that are rich, warm and made to flatter your skin tone Color Sensational The Creams lipsticks now include your favorite shades from the Vivids and Buffs collections.", "https://www.amazon.in/Maybelline-Sensational-Powder-Lipstick-Cherry/dp/B07YXG7LSV/ref=sr_1_1?crid=3IJQG46I8MI21&dib=eyJ2IjoiMSJ9.EFdP8swZrfqj1rSA6vUBbgTio0AzFqaG-afhFu2-nZGUDSrPAyWO5gORT2v_2blRhseMA4MuhZsOv4bMFt6vnUsXOKLVL4I2Z9ANvacTu5WwZPDmD3U4w_38DKFOtzGAYiauL2KBWxd9BIBpA9nyApPqV-Eh65itowxYje1f7lSuMq4xiDL0maeQhy2EICUCyOB3O2JjYmOFGojyT-05yYSW5oOMxVHosT8ZeRYZ-ao6uVADmOramKq2pdiaadyle8dreZMYP9OzCfwenJogbktEOxEkRYP_QkfRd7YnTag.BDVTqPI6NLrd7_Tg4gxj4rm55UaxnApJumK4sm8_oTY&dib_tag=se&keywords=yellow%2Bcolor%2Blipstick%2Bmaybelline&qid=1709892219&s=beauty&sprefix=yellow%2Bcolor%2Blipstick%2Bmabellin%2Cbeauty%2C336&sr=1-1&th=1"));
        items.add(new PopularDomain(24, "Maybelline Color Sensational Lipstick Crimson Race", "lips_4_1", "lips_4_2", "lips_4_3", 4.1, 34058, 1269, "Color Sensational The Creams delivers crisp color and smooth lips - Infused with Shea Butter, Color Sensational The Creams takes on a new feeling from the first touch of the packaging to the first swipe Color Sensational The Creams lipsticks deliver pure color pigments and Shea Butter for vibrant color, smooth lips and a creamy finish that does not bleed or feather Highly pigmented lip color with a creamy smooth glide during application that leaves lips feeling hydrated, nurtured, and conditioned Available in sensational lipstick shades you know and love - nudes, pinks, reds and plums - that are rich, warm and made to flatter your skin tone Color Sensational The Creams lipsticks now include your favorite shades from the Vivids and Buffs collections.", "https://www.amazon.in/Maybelline-Sensational-Powder-Lipstick-Cherry/dp/B07YXG19S3/ref=sr_1_1?crid=3IJQG46I8MI21&dib=eyJ2IjoiMSJ9.EFdP8swZrfqj1rSA6vUBbgTio0AzFqaG-afhFu2-nZGUDSrPAyWO5gORT2v_2blRhseMA4MuhZsOv4bMFt6vnUsXOKLVL4I2Z9ANvacTu5WwZPDmD3U4w_38DKFOtzGAYiauL2KBWxd9BIBpA9nyApPqV-Eh65itowxYje1f7lSuMq4xiDL0maeQhy2EICUCyOB3O2JjYmOFGojyT-05yYSW5oOMxVHosT8ZeRYZ-ao6uVADmOramKq2pdiaadyle8dreZMYP9OzCfwenJogbktEOxEkRYP_QkfRd7YnTag.BDVTqPI6NLrd7_Tg4gxj4rm55UaxnApJumK4sm8_oTY&dib_tag=se&keywords=yellow%2Bcolor%2Blipstick%2Bmaybelline&qid=1709892219&s=beauty&sprefix=yellow%2Bcolor%2Blipstick%2Bmabellin%2Cbeauty%2C336&sr=1-1&th=1"));
        items.add(new PopularDomain(25, "Maybelline Color Sensational Lipstick Bare Reveal", "lips_5_1", "lips_5_2", "lips_5_3", 4.1, 34058, 1793, "Color Sensational The Creams delivers crisp color and smooth lips - Infused with Shea Butter, Color Sensational The Creams takes on a new feeling from the first touch of the packaging to the first swipe Color Sensational The Creams lipsticks deliver pure color pigments and Shea Butter for vibrant color, smooth lips and a creamy finish that does not bleed or feather Highly pigmented lip color with a creamy smooth glide during application that leaves lips feeling hydrated, nurtured, and conditioned Available in sensational lipstick shades you know and love - nudes, pinks, reds and plums - that are rich, warm and made to flatter your skin tone Color Sensational The Creams lipsticks now include your favorite shades from the Vivids and Buffs collections.", "https://www.amazon.in/Maybelline-Sensational-Powder-Lipstick-Cherry/dp/B07YXFYM3Z/ref=sr_1_1?crid=3IJQG46I8MI21&dib=eyJ2IjoiMSJ9.EFdP8swZrfqj1rSA6vUBbgTio0AzFqaG-afhFu2-nZGUDSrPAyWO5gORT2v_2blRhseMA4MuhZsOv4bMFt6vnUsXOKLVL4I2Z9ANvacTu5WwZPDmD3U4w_38DKFOtzGAYiauL2KBWxd9BIBpA9nyApPqV-Eh65itowxYje1f7lSuMq4xiDL0maeQhy2EICUCyOB3O2JjYmOFGojyT-05yYSW5oOMxVHosT8ZeRYZ-ao6uVADmOramKq2pdiaadyle8dreZMYP9OzCfwenJogbktEOxEkRYP_QkfRd7YnTag.BDVTqPI6NLrd7_Tg4gxj4rm55UaxnApJumK4sm8_oTY&dib_tag=se&keywords=yellow%2Bcolor%2Blipstick%2Bmaybelline&qid=1709892219&s=beauty&sprefix=yellow%2Bcolor%2Blipstick%2Bmabellin%2Cbeauty%2C336&sr=1-1&th=1"));
        items.add(new PopularDomain(26, "Maybelline Color Sensational Lipstick Naked Dare", "lips_6_1", "lips_6_2", "lips_6_3", 4.1, 34058, 0, "Color Sensational The Creams delivers crisp color and smooth lips - Infused with Shea Butter, Color Sensational The Creams takes on a new feeling from the first touch of the packaging to the first swipe Color Sensational The Creams lipsticks deliver pure color pigments and Shea Butter for vibrant color, smooth lips and a creamy finish that does not bleed or feather Highly pigmented lip color with a creamy smooth glide during application that leaves lips feeling hydrated, nurtured, and conditioned Available in sensational lipstick shades you know and love - nudes, pinks, reds and plums - that are rich, warm and made to flatter your skin tone Color Sensational The Creams lipsticks now include your favorite shades from the Vivids and Buffs collections.", "https://www.amazon.in/Maybelline-Sensational-Powder-Lipstick-Cherry/dp/B07YXGG4D1/ref=sr_1_1?crid=3IJQG46I8MI21&dib=eyJ2IjoiMSJ9.EFdP8swZrfqj1rSA6vUBbgTio0AzFqaG-afhFu2-nZGUDSrPAyWO5gORT2v_2blRhseMA4MuhZsOv4bMFt6vnUsXOKLVL4I2Z9ANvacTu5WwZPDmD3U4w_38DKFOtzGAYiauL2KBWxd9BIBpA9nyApPqV-Eh65itowxYje1f7lSuMq4xiDL0maeQhy2EICUCyOB3O2JjYmOFGojyT-05yYSW5oOMxVHosT8ZeRYZ-ao6uVADmOramKq2pdiaadyle8dreZMYP9OzCfwenJogbktEOxEkRYP_QkfRd7YnTag.BDVTqPI6NLrd7_Tg4gxj4rm55UaxnApJumK4sm8_oTY&dib_tag=se&keywords=yellow%2Bcolor%2Blipstick%2Bmaybelline&qid=1709892219&s=beauty&sprefix=yellow%2Bcolor%2Blipstick%2Bmabellin%2Cbeauty%2C336&sr=1-1&th=1"));
        items.add(new PopularDomain(27, "Maybelline Color Sensational Matte Lipstick", "lips_7_1", "lips_7_2", "lips_7_3", 4.1, 34058, 1022, "Color Sensational The Creams delivers crisp color and smooth lips - Infused with Shea Butter, Color Sensational The Creams takes on a new feeling from the first touch of the packaging to the first swipe Color Sensational The Creams lipsticks deliver pure color pigments and Shea Butter for vibrant color, smooth lips and a creamy finish that does not bleed or feather Highly pigmented lip color with a creamy smooth glide during application that leaves lips feeling hydrated, nurtured, and conditioned Available in sensational lipstick shades you know and love - nudes, pinks, reds and plums - that are rich, warm and made to flatter your skin tone Color Sensational The Creams lipsticks now include your favorite shades from the Vivids and Buffs collections.", "https://www.amazon.in/Maybelline-Sensational-Powder-Lipstick-Cherry/dp/B01DPA81IE/ref=sr_1_1?crid=3IJQG46I8MI21&dib=eyJ2IjoiMSJ9.EFdP8swZrfqj1rSA6vUBbgTio0AzFqaG-afhFu2-nZGUDSrPAyWO5gORT2v_2blRhseMA4MuhZsOv4bMFt6vnUsXOKLVL4I2Z9ANvacTu5WwZPDmD3U4w_38DKFOtzGAYiauL2KBWxd9BIBpA9nyApPqV-Eh65itowxYje1f7lSuMq4xiDL0maeQhy2EICUCyOB3O2JjYmOFGojyT-05yYSW5oOMxVHosT8ZeRYZ-ao6uVADmOramKq2pdiaadyle8dreZMYP9OzCfwenJogbktEOxEkRYP_QkfRd7YnTag.BDVTqPI6NLrd7_Tg4gxj4rm55UaxnApJumK4sm8_oTY&dib_tag=se&keywords=yellow%2Bcolor%2Blipstick%2Bmaybelline&qid=1709892219&s=beauty&sprefix=yellow%2Bcolor%2Blipstick%2Bmabellin%2Cbeauty%2C336&sr=1-1&th=1"));
        items.add(new PopularDomain(28, "Maybelline New York Color Sensational Rebel Bloom Lipstick", "lips_8_1", "lips_8_2", "lips_8_3", 4.1, 34058, 5224, "MATTE FINISH MAYBELLINE LIPSTICK: This velvety, hydrating matte lipstick goes on in one swipe, delivering bold, intense color that lasts. Formulated with honey nectar for a sensuous finish.COLOR SENSATIONAL LIPSTICK: For hyperpigmented lip color in an ultra-hydrating formula, look no further than Color Sensational lipsticks. Available in matte, satin, & gloss & shades from nude to bold black.MAYBELLINE LIPS: Layer on intense color that lasts with Superstay 24 hr Lip color, slay a matte lip with SuperStay Matte Ink Liquid Lipstick, renew with Baby Lips Moisturizing Lip Balm, or add gloss to any color with Clear Lip Gloss Topcoat.MAYBELLINE HAS WHAT YOU NEED to create any look—foundation, bb creams, concealers, & highlighters for the perfect canvas, eyeshadows, brow pencils, & eyeliners for any eye look & lip products, from showstopping matte lipstick to au natural lip balms. REMOVE MAYBELLINE MAKEUP WITH MICELLAR WATER: Use Garnier Micellar Water as a gentle makeup remover at night, & as a facial cleanser in the morning to prep skin for Maybelline makeup.", "https://www.amazon.in/Maybelline-Sensational-Powder-Lipstick-Cherry/dp/B00PFCS5L4/ref=sr_1_1?crid=3IJQG46I8MI21&dib=eyJ2IjoiMSJ9.EFdP8swZrfqj1rSA6vUBbgTio0AzFqaG-afhFu2-nZGUDSrPAyWO5gORT2v_2blRhseMA4MuhZsOv4bMFt6vnUsXOKLVL4I2Z9ANvacTu5WwZPDmD3U4w_38DKFOtzGAYiauL2KBWxd9BIBpA9nyApPqV-Eh65itowxYje1f7lSuMq4xiDL0maeQhy2EICUCyOB3O2JjYmOFGojyT-05yYSW5oOMxVHosT8ZeRYZ-ao6uVADmOramKq2pdiaadyle8dreZMYP9OzCfwenJogbktEOxEkRYP_QkfRd7YnTag.BDVTqPI6NLrd7_Tg4gxj4rm55UaxnApJumK4sm8_oTY&dib_tag=se&keywords=yellow%2Bcolor%2Blipstick%2Bmaybelline&qid=1709892219&s=beauty&sprefix=yellow%2Bcolor%2Blipstick%2Bmabellin%2Cbeauty%2C336&sr=1-1&th=1"));
        items.add(new PopularDomain(29, "Maybelline New York Color Sensational Creamy Matte Lipstick", "lips_9_1", "lips_9_2", "lips_9_3", 4.1, 34058, 1847, "Super-saturated pigments take fresh picked pastels to a new bright Never dull, washed out or shy Honey nectar adds a sumptuous feel This Product is Shipped from USA within 7 to 14 days of reciept of order.", "https://www.amazon.in/Maybelline-Sensational-Powder-Lipstick-Cherry/dp/B00YJJWLLE/ref=sr_1_1?crid=3IJQG46I8MI21&dib=eyJ2IjoiMSJ9.EFdP8swZrfqj1rSA6vUBbgTio0AzFqaG-afhFu2-nZGUDSrPAyWO5gORT2v_2blRhseMA4MuhZsOv4bMFt6vnUsXOKLVL4I2Z9ANvacTu5WwZPDmD3U4w_38DKFOtzGAYiauL2KBWxd9BIBpA9nyApPqV-Eh65itowxYje1f7lSuMq4xiDL0maeQhy2EICUCyOB3O2JjYmOFGojyT-05yYSW5oOMxVHosT8ZeRYZ-ao6uVADmOramKq2pdiaadyle8dreZMYP9OzCfwenJogbktEOxEkRYP_QkfRd7YnTag.BDVTqPI6NLrd7_Tg4gxj4rm55UaxnApJumK4sm8_oTY&dib_tag=se&keywords=yellow%2Bcolor%2Blipstick%2Bmaybelline&qid=1709892219&s=beauty&sprefix=yellow%2Bcolor%2Blipstick%2Bmabellin%2Cbeauty%2C336&sr=1-1&th=1"));
        items.add(new PopularDomain(30, "Maybelline New York Color Sensational Rebel Bloom Lipstick -Power Peony", "lips_10_1", "lips_10_2", "lips_1_3", 4.1, 34058, 2893, "The Maybelline Color Sensational Creamy Mattes Lipstick has a unique, velvety matte cream formula that offers a non-drying & un-crackable finish that stays comfortably on your lips through the day These hydrating Maybelline lipstick shades are are infused with honey nectar to keep your lips moisturized all day long. The Colour Sensation lipsticks glide on your lips smoothly for a comfortable wear.The Color Sensational Creamy Matte Lipsticks are available in 30+ pigmented shades, from subtle nudes to bold reds and everything in between.Pair the Color Sensational Creamy Matte Lipstick with a nourishing Maybelline Lip Balm for colour and care!", "https://www.amazon.in/Maybelline-Sensational-Powder-Lipstick-Cherry/dp/B00PFCS5QY/ref=sr_1_1?crid=3IJQG46I8MI21&dib=eyJ2IjoiMSJ9.EFdP8swZrfqj1rSA6vUBbgTio0AzFqaG-afhFu2-nZGUDSrPAyWO5gORT2v_2blRhseMA4MuhZsOv4bMFt6vnUsXOKLVL4I2Z9ANvacTu5WwZPDmD3U4w_38DKFOtzGAYiauL2KBWxd9BIBpA9nyApPqV-Eh65itowxYje1f7lSuMq4xiDL0maeQhy2EICUCyOB3O2JjYmOFGojyT-05yYSW5oOMxVHosT8ZeRYZ-ao6uVADmOramKq2pdiaadyle8dreZMYP9OzCfwenJogbktEOxEkRYP_QkfRd7YnTag.BDVTqPI6NLrd7_Tg4gxj4rm55UaxnApJumK4sm8_oTY&dib_tag=se&keywords=yellow%2Bcolor%2Blipstick%2Bmaybelline&qid=1709892219&s=beauty&sprefix=yellow%2Bcolor%2Blipstick%2Bmabellin%2Cbeauty%2C336&sr=1-1&th=1"));

        binding.productList.setLayoutManager(new LinearLayoutManager(this,LinearLayoutManager.VERTICAL,false));
        binding.productList.setAdapter(new PopularAdapter(items,this));
    }
}